# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('name', models.CharField(max_length=600)),
                ('subject', models.CharField(max_length=600)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
